// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanBinCommands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCleanCommandsPackageString = "f1dcc2f3-4efd-4579-9566-b29ef5f54d2a";
        public const string guidCleanProjectCommandPackageCmdSetString = "a16645a7-f9c7-48c0-9dab-92afd47265c4";
        public const string guidCleanSolutionCommandPackageCmdSetString = "a16645a7-f9c7-48c0-9dab-92afd47265c5";
        public static Guid guidCleanCommandsPackage = new Guid(guidCleanCommandsPackageString);
        public static Guid guidCleanProjectCommandPackageCmdSet = new Guid(guidCleanProjectCommandPackageCmdSetString);
        public static Guid guidCleanSolutionCommandPackageCmdSet = new Guid(guidCleanSolutionCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CleanProjectCommandMenuGroup = 0x1020;
        public const int CleanProjectCommandId = 0x0100;
        public const int CleanSolutionCommandMenuGroup = 0x1021;
        public const int CleanSolutionCommandId = 0x0101;
    }
}
